const teamsTemplate = [
  {
    name: "Oxted & District",
    ground: ["Master Park", "Bletchingley FC"],
    years: [
      {
        year: "2023/24",
        status: "On going",
        league: "65f1b8e740fdc5a1088e064b",
        players: [],
      },
    ],
  },
  {
    name: "Crawley Devils",
    ground: ["Warden park secondary academy 3G"],
    years: [
      {
        year: "2023/24",
        status: "On going",
        league: "65f1b8e740fdc5a1088e064b",
        players: [],
      },
    ],
  },
];

const playerTemplate = {
  fistName: "Lee",
  lastName: "Peacock",
  number: 0,
  postiion: "",
  years: [
    {
      year: "2023/24",
      status: "On going",
      stats: [
        {
          team: "65f1ba72de0e70288a786642",
          appearances: 14,
          goals: 4,
          started: 9,
          yellowCards: 0,
          redCards: 0,
          playerofMatch: 0,
          cleanSheet: 0,
          assists: 0,
        },
      ],
    },
  ],
};

const leagueTemplate = [
  {
    league: "Premier League",
    years: [
      {
        year: "2023/24",
        status: "On going",
        teams: [
          "65f1ba72de0e70288a786642",
          "65f1e64bc5a1935b407d6c07",
          "65f1f64b00e92c4d890fa391",
        ],
        fixtures: [
          {
            home: "Battle Town",
            away: "Westfield",
            dateTime: "2023-09-02T14:00:00",
            venue: "Bexhill College 3G",
            status: "completed",
            events: [],
          },
          {
            home: "Copthorne II",
            away: " Sedlescombe Rangers",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Crawley Devils",
            away: "Rotherfield",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Cuckfield Rangers",
            away: "Reigate Priory",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Eastbourne United Association",
            away: "Oxted & District",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Holland Sports",
            away: "Lindfield",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Oxted & District",
            away: "Holland Sport",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Reigate Priory",
            away: "Eastbourne United Association",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Rotherfield",
            away: "Cuckfield Rangers",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Westfield",
            away: "Copthorne II",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Sedlescombe Rangers",
            away: "Crawley Devils",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Balcombe",
            away: "Battle Town",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Copthorne II",
            away: "Balcombe",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Crawley Devils",
            away: "Westfield",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Cuckfield Rangers",
            away: "Sedlescombe Rangers",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Eastbourne United Association",
            away: "Rotherfield",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Holland Sports",
            away: "Reigate Priory",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Lindfield",
            away: "Oxted & District",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Reigate Priory",
            away: "Lindfield",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Rotherfield",
            away: "Holland Sports",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Sedlescombe Rangers",
            away: "Eastbourne United Association",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Westfield",
            away: "Cuckfield Rangers",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Balcombe",
            away: "Crawley Devils",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Battle Town",
            away: "Copthorne II",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Crawley Devils",
            away: "Battle Town",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Cuckfield Rangers",
            away: "Balcombe",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Eastbourne United Association",
            away: "Westfield",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Holland Sports",
            away: "Sedlescombe Rangers",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Lindfield",
            away: "Rotherfield",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Oxted & District",
            away: "Reigate Priory",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Rotherfield",
            away: "Oxted & District",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Sedlescombe Rangers",
            away: "Lindfield",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Westifeld",
            away: "Holland Sports",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Balcombe",
            away: "Eastbourne United Association",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Battle Town",
            away: "Cuckfield Rangers",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Balcombe",
            away: "Copthorne II",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Balcombe",
            away: "Cuckfield Rangers",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Balcombe",
            away: "Holland Sports",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Balcombe",
            away: "Lindfield",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Balcombe",
            away: "Oxted & District",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Balcombe",
            away: "Reigate Priory",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Balcombe",
            away: "Rotherfield",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Balcombe",
            away: "Sedlescombe Rangers",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Balcombe",
            away: "Westfield",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Battle Town",
            away: "Balcombe",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Battle Town",
            away: "Crawley Devils",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Battle Town",
            away: "Eastbourne United Association",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Battle Town",
            away: "Holland Sports",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Battle Town",
            away: "Lindfield",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Battle Town",
            away: "Oxted & District",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Battle Town",
            away: "Reigate Priory",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Battle Town",
            away: "Rotherfield",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Battle Town",
            away: "Sedlescombe Rangers",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Crawley Devils",
            away: "Balcombe",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Crawley Devils",
            away: "Copthorne II",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Crawley Devils",
            away: "Cuckfield Rangers",
            dateTime: "Eastbourne United Association",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Crawley Devils",
            away: "Holland Sports",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Crawley Devils",
            away: "Lindfield",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Crawley Devils",
            away: "Oxted & District",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Crawley Devils",
            away: "Reigate Priory",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Crawley Devils",
            away: "Sedlescombe Rangers",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Copthorne II",
            away: "Battle Town",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Copthorne II",
            away: "Crawley Devils",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Copthorne II",
            away: "Cuckfield Rangers",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Copthorne II",
            away: "Eastbourne United Association",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Copthorne II",
            away: "Holland Sports",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Copthorne II",
            away: "Lindfield",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Copthorne II",
            away: "Oxted & District",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Copthorne II",
            away: "Reigate Priory",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Copthorne II",
            away: "Rotherfield",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Copthorne II",
            away: "Westfield",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Eastbourne United Association",
            away: "Balcombe",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Eastbourne United Association",
            away: "Battle Town",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Eastbourne United Association",
            away: "Copthorne II",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Eastbourne United Association",
            away: "Crawley Devils",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Eastbourne United Association",
            away: "Cuckfield Rangers",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Eastbourne United Association",
            away: "Holland Sports",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Eastbourne United Association",
            away: "Lindfield",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Eastbourne United Association",
            away: "Reigate Priory",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Eastbourne United Association",
            away: "Sedlescombe Rangers",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Cuckfield Rangers",
            away: "Battle Town",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Cuckfield Rangers",
            away: "Copthorne II",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Cuckfield Rangers",
            away: "Crawley Devils",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Cuckfield Rangers",
            away: "Eastbourne United Association",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Cuckfield Rangers",
            away: "Holland Sports",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Cuckfield Rangers",
            away: "Lindfield",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Cuckfield Rangers",
            away: "Oxted & District",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Cuckfield Rangers",
            away: "Rotherfield",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Cuckfield Rangers",
            away: "Westfield",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Holland Sports",
            away: "Balcombe",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Holland Sports",
            away: "Battle Town",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Holland Sports",
            away: "Copthorne II",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Holland Sports",
            away: "Crawley Devils",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Holland Sports",
            away: "Cuckfield Rangers",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Holland Sports",
            away: "Eastbourne United Association",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Holland Sports",
            away: "Oxted & District",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Holland Sports",
            away: "Rotherfield",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Holland Sports",
            away: "Westfield",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Lindfield",
            away: "Balcombe",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Lindfield",
            away: "Battle Town",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Lindfield",
            away: "Copthorne II",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Lindfield",
            away: "Crawley Devils",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Lindfield",
            away: "Cuckfield Rangers",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Lindfield",
            away: "Eastbourne United Association",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Lindfield",
            away: "Holland Sports",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Lindfield",
            away: "Reigate Priory",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Lindfield",
            away: "Sedlescombe Rangers",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Lindfield",
            away: "Westfield",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Oxted & District",
            away: "Balcombe",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Oxted & District",
            away: "Battle Town",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Oxted & District",
            away: "Copthorne II",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Oxted & District",
            away: "Crawley Devils",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Oxted & District",
            away: "Cuckfield Rangers",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Oxted & District",
            away: "Eastbourne United Association",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Oxted & District",
            away: "Lindfield",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Oxted & District",
            away: "Rotherfield",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Oxted & District",
            away: "Sedlescombe Rangers",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Oxted & District",
            away: "Westfield",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Reigate Priory",
            away: "Balcombe",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Reigate Priory",
            away: "Battle Town",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Reigate Priory",
            away: "Copthorne II",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Reigate Priory",
            away: "Crawley Devils",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Reigate Priory",
            away: "Cuckfield Rangers",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Reigate Priory",
            away: "Holland Sports",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Reigate Priory",
            away: "Oxted & District",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Reigate Priory",
            away: "Rotherfield",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Reigate Priory",
            away: "Sedlescombe Rangers",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Reigate Priory",
            away: "Westfield",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Rotherfield",
            away: "Balcombe",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Rotherfield",
            away: "Battle Town",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Rotherfield",
            away: "Copthorne II",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Rotherfield",
            away: "Crawley Devils",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Rotherfield",
            away: "Eastbourne United Association",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Rotherfield",
            away: "Lindfield",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Rotherfield",
            away: "Reigate Priory",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Rotherfield",
            away: "Sedlescombe Rangers",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Rotherfield",
            away: "Westfield",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Sedlescombe Rangers",
            away: "Balcombe",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Sedlescombe Rangers",
            away: "Battle Town",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Sedlescombe Rangers",
            away: "Copthorne II",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Sedlescombe Rangers",
            away: "Cuckfield Rangers",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Sedlescombe Rangers",
            away: "Holland Sports",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Sedlescombe Rangers",
            away: "Oxted & District",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Sedlescombe Rangers",
            away: "Reigate Priory",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Sedlescombe Rangers",
            away: "Rotherfield",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Sedlescombe Rangers",
            away: "Westfield",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Westfield",
            away: "Balcombe",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Westfield",
            away: "Battle Town",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Westfield",
            away: "Crawley Devils",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Westfield",
            away: "Eastbourne United Association",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Westfield",
            away: "Lindfield",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Westfield",
            away: "Oxted & District",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Westfield",
            away: "Reigate Priory",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Westfield",
            away: "Rotherfield",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
          {
            home: "Westfield",
            away: "Sedlescombe Rangers",
            dateTime: "",
            venue: "",
            status: "",
            events: [],
          },
        ],
      },
    ],
  },
];
